# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [81]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

df = pd.read_csv(url, sep='\t')

### Step 4. See the first 10 entries

In [9]:
df.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [17]:
# Solution 1
df.shape[0]

4622

In [18]:
# Solution 2
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

### Step 6. What is the number of columns in the dataset?

In [20]:
len(df.columns)

5

### Step 7. Print the name of all the columns.

In [21]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [22]:
df.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [26]:
df['item_name'].mode()

0    Chicken Bowl
Name: item_name, dtype: object

### Step 10. For the most-ordered item, how many items were ordered?

In [40]:
chickenBowlOrder = df[df['item_name'] == 'Chicken Bowl']
totalOrders = sum(chickenBowlOrder['quantity'])
totalOrders

761

### Step 11. What was the most ordered item in the choice_description column?

In [60]:
groupByChoiceDesc = df.groupby('choice_description').sum()
groupByChoiceDesc = groupByChoiceDesc.sort_values('quantity', ascending=False)
groupByChoiceDesc.head(1)

,order_id,quantity,item_name,item_price
choice_description,,,,
[Diet Coke],123455,159,Canned SodaCanned SodaCanned Soda6 Pack Soft D...,$2.18 $1.09 $1.09 $6.49 $2.18 $1.25 $1.09 $6.4...

### Step 12. How many items were orderd in total?

In [63]:
groupByChoiceDesc['quantity'].sum()

np.int64(3590)

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [64]:
df.item_price.dtype

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [82]:
dollarizer = lambda x: float(x[1:-1])
df.item_price = df.item_price.apply(dollarizer)
df.item_price.head(10)

0     2.39
1     3.39
2     3.39
3     2.39
4    16.98
5    10.98
6     1.69
7    11.75
8     9.25
9     9.25
Name: item_price, dtype: float64

#### Step 13.c. Check the item price type

In [83]:
df.item_price.dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [86]:
A = df.item_price*df.quantity
A.sum()

np.float64(39237.02)

### Step 15. How many orders were made in the period?

In [89]:
df.order_id.unique().max()

np.int64(1834)

### Step 16. What is the average revenue amount per order?

In [103]:
# Solution 1
df['revenue'] = df.item_price * df.quantity
df.groupby('order_id').sum()['revenue'].mean()

np.float64(21.39423118865867)

In [4]:
# Solution 2

### Step 17. How many different items are sold?

In [113]:
df.item_name.value_counts().count()

np.int64(50)